name: Java CI with Gradle

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build
      run: ./gradlew build

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      #  workload_identity_provider: 'projects/136465850127/locations/global/workloadIdentityPools/gha-demo-pool/providers/gha-demo-provider'
      #  service_account: 'github-actions-demo@github-actions-demo-400806.iam.gserviceaccount.com'
    - run: echo "${{ steps.auth.outputs.access_token }}"
    - uses: 'docker/login-action@v1'
      with:
        registry: 'asia-south1-docker.pkg.dev'
        username: 'oauth2accesstoken'
        password: '${{ steps.auth.outputs.access_token }}'
        
    - name: Docker Build
      run: docker build -t asia-south1-docker.pkg.dev/github-actions-demo-400806/sample-java-app/hello-world:latest .

    - name: Push Image to Google Cloud Artifact Registry
      run: docker push asia-south1-docker.pkg.dev/github-actions-demo-400806/sample-java-app/hello-world:latest

    - name: Install Kubectl
      uses: azure/setup-kubectl@v2.0
      with:
       version: 'v1.27.0' # default is latest stable
      id: install

    - name: Deploy
      run: |
        gcloud container clusters get-credentials cluster-1 --zone us-central1-a --project github-actions-demo-400806
        kubectl get nodes
  #  - name: Configure Docker to use gcloud
   #   run: |
    #    gcloud auth configure-docker asia-south1-docker.pkg.dev
    #    docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/sample-java-app/hello-world:latest .
     #   docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/sample-java-app/hello-world:latest
          
  #  - name: Push to Google Artifact Registry
  #    run: docker push asia-south1-docker.pkg.dev/github-actions-demo-400806/sample-java-app/hello-world:latest
    

    
    
