name: Java CI with Gradle

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build
      run: ./gradlew build

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

   # - name: Docker Build
   #   run: docker build -t asia-south1-docker.pkg.dev/github-actions-demo-400806/sample-java-app/hello-world:latest .

    - name: Configure Docker to use gcloud
      run: |
        gcloud auth configure-docker asia-south1-docker.pkg.dev
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/sample-java-app/hello-world:latest .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/sample-java-app/hello-world:latest
          
  #  - name: Push to Google Artifact Registry
  #    run: docker push asia-south1-docker.pkg.dev/github-actions-demo-400806/sample-java-app/hello-world:latest
    

    
    
