name: Java CI with Gradle

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    
    - name: Execute Gradle build
      run: ./gradlew build

    - name: Set up Google Cloud SDK
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: 8b4e0880240c2cdcff3a09bf54411204178677bb

    - name: Docker Build
      run: docker build -t asia-south1-docker.pkg.dev/github-actions-demo-400806/sample-java-app/hello-world:latest .

    - name: Configure Docker to use gcloud
      run: |
        gcloud auth configure-docker asia-south1-docker.pkg.dev
        docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/sample-java-app/hello-world:latest .
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/sample-java-app/hello-world:latest
          
    - name: Push to Google Artifact Registry
      run: docker push asia-south1-docker.pkg.dev/github-actions-demo-400806/sample-java-app/hello-world:latest
    

    
    
